// Generated by `npm run images` from app/assets/images/source. Do not edit.

import bath640 from './bath-640.webp';
import bath960 from './bath-960.webp';
import bath1440 from './bath-1440.webp';
import grocery2640 from './grocery-2-640.webp';
import grocery2960 from './grocery-2-960.webp';
import grocery21440 from './grocery-2-1440.webp';
import plane640 from './plane-640.webp';
import plane960 from './plane-960.webp';
import plane1440 from './plane-1440.webp';
import rain640 from './rain-640.webp';
import rain960 from './rain-960.webp';
import rain1440 from './rain-1440.webp';
import swimmer640 from './swimmer-640.webp';
import swimmer960 from './swimmer-960.webp';
import swimmer1440 from './swimmer-1440.webp';
import waterLily640 from './water_lily-640.webp';
import waterLily960 from './water_lily-960.webp';
import waterLily1440 from './water_lily-1440.webp';

export type LocalImage = {
  src: string;
  srcSet: string;
  width: number;
  height: number;
};

export const bath: LocalImage = {
  src: bath1440,
  srcSet: `${bath640} 640w, ${bath960} 960w, ${bath1440} 1440w`,
  width: 1440,
  height: 960,
};

export const grocery2: LocalImage = {
  src: grocery21440,
  srcSet: `${grocery2640} 640w, ${grocery2960} 960w, ${grocery21440} 1440w`,
  width: 1440,
  height: 960,
};

export const plane: LocalImage = {
  src: plane1440,
  srcSet: `${plane640} 640w, ${plane960} 960w, ${plane1440} 1440w`,
  width: 1440,
  height: 960,
};

export const rain: LocalImage = {
  src: rain1440,
  srcSet: `${rain640} 640w, ${rain960} 960w, ${rain1440} 1440w`,
  width: 1440,
  height: 955,
};

export const swimmer: LocalImage = {
  src: swimmer1440,
  srcSet: `${swimmer640} 640w, ${swimmer960} 960w, ${swimmer1440} 1440w`,
  width: 1440,
  height: 960,
};

export const waterLily: LocalImage = {
  src: waterLily1440,
  srcSet: `${waterLily640} 640w, ${waterLily960} 960w, ${waterLily1440} 1440w`,
  width: 1440,
  height: 953,
};
