import {readdir, writeFile} from 'node:fs/promises';
import {basename, extname, join} from 'node:path';
import {fileURLToPath} from 'node:url';
import sharp from 'sharp';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const SOURCE_DIR = join(ROOT, 'app/assets/images/source');
const OUTPUT_DIR = join(ROOT, 'app/assets/images');
const MANIFEST = join(OUTPUT_DIR, 'generated.ts');

const WIDTHS = [640, 960, 1440];
const QUALITY = 72;

function camelCase(name) {
  return name.replace(/[-_](.)/g, (_, char) => char.toUpperCase());
}

async function variantsFor(file) {
  const name = basename(file, extname(file));
  const image = sharp(join(SOURCE_DIR, file));
  const {width: sourceWidth, height: sourceHeight} = await image.metadata();

  const widths = WIDTHS.filter((width) => width <= sourceWidth);
  if (widths.length === 0) widths.push(sourceWidth);

  const variants = await Promise.all(
    widths.map(async (width) => {
      const output = `${name}-${width}.webp`;
      const {size} = await image
        .clone()
        .resize({width})
        .webp({quality: QUALITY, effort: 6})
        .toFile(join(OUTPUT_DIR, output));
      return {width, output, size};
    }),
  );

  return {
    name,
    identifier: camelCase(name),
    aspectRatio: sourceHeight / sourceWidth,
    variants,
  };
}

function renderManifest(images) {
  const imports = images
    .flatMap(({identifier, variants}) =>
      variants.map(
        ({width, output}) =>
          `import ${identifier}${width} from './${output}';`,
      ),
    )
    .join('\n');

  const exports = images
    .map(({identifier, aspectRatio, variants}) => {
      const largest = variants[variants.length - 1];
      const srcSet = variants
        .map(({width}) => `\${${identifier}${width}} ${width}w`)
        .join(', ');
      return [
        `export const ${identifier}: LocalImage = {`,
        `  src: ${identifier}${largest.width},`,
        `  srcSet: \`${srcSet}\`,`,
        `  width: ${largest.width},`,
        `  height: ${Math.round(largest.width * aspectRatio)},`,
        `};`,
      ].join('\n');
    })
    .join('\n\n');

  return [
    '// Generated by `npm run images` from app/assets/images/source. Do not edit.',
    '',
    imports,
    '',
    'export type LocalImage = {',
    '  src: string;',
    '  srcSet: string;',
    '  width: number;',
    '  height: number;',
    '};',
    '',
    exports,
    '',
  ].join('\n');
}

const files = (await readdir(SOURCE_DIR)).filter((file) =>
  /\.(jpe?g|png|webp|tiff?)$/i.test(file),
);

const images = [];
for (const file of files.sort()) {
  const image = await variantsFor(file);
  images.push(image);
  for (const {width, size} of image.variants) {
    console.log(`${image.name} ${width}w — ${(size / 1024).toFixed(0)} kB`);
  }
}

await writeFile(MANIFEST, renderManifest(images));
console.log(`\n${images.length} images → ${MANIFEST}`);
